-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 20:54:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbcyber
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcyber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcyber` ;
USE `dbcyber` ;

-- -----------------------------------------------------
-- Table `dbcyber`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `idClientes_UNIQUE` (`idClientes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcyber`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `tipo_usr`  INT NULL,
  `nombre`VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `idusuarios_UNIQUE` (`idusuarios` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcyber`.`tipo_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`tipo_equipo` (
  `idtipo_equipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_equipo`),
  UNIQUE INDEX `idtipo_equipo_UNIQUE` (`idtipo_equipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcyber`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idmarca`),
  UNIQUE INDEX `idmarca_UNIQUE` (`idmarca` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcyber`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`Producto` (
  `idProducto` INT NOT NULL,
  `idtipo_equipo` INT NOT NULL,
  `idmarca` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_1_idx` (`idtipo_equipo` ASC),
  INDEX `fk_Producto_2_idx` (`idmarca` ASC),
  CONSTRAINT `fk_Producto_1`
    FOREIGN KEY (`idtipo_equipo`)
    REFERENCES `dbcyber`.`tipo_equipo` (`idtipo_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_2`
    FOREIGN KEY (`idmarca`)
    REFERENCES `dbcyber`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcyber`.`Trabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`Trabajos` (
  `idTrabajos` INT NOT NULL AUTO_INCREMENT,
  `idClientes` INT NOT NULL,
  `idusuarios` INT NOT NULL,
  `fecha_recepcion` DATE NOT NULL,
  `fecha_estimada` DATE NOT NULL,
  `estatus` INT NOT NULL,
  `fecha_entrega` DATE NULL,
  `Total` DECIMAL(10) NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idTrabajos`),
  UNIQUE INDEX `idTrabajos_UNIQUE` (`idTrabajos` ASC),
  INDEX `fk_Trabajos_1_idx` (`idClientes` ASC) ,
  INDEX `fk_Trabajos_2_idx` (`idusuarios` ASC) ,
  INDEX `fk_Trabajos_3_idx` (`idProducto` ASC),
  CONSTRAINT `fk_Trabajos_1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `dbcyber`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajos_2`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `dbcyber`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajos_3`
    FOREIGN KEY (`idProducto`)
    REFERENCES `dbcyber`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcyber`.`Reparaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`Reparaciones` (
  `idReparaciones` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `costo` DECIMAL(15) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReparaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcyber`.`actulisaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcyber`.`actulisaciones` (
  `idactulisaciones` INT NOT NULL AUTO_INCREMENT,
  `idTrabajos` INT NOT NULL,
  `idreparaciones` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `presupuesto` DECIMAL(15) NOT NULL,
  PRIMARY KEY (`idactulisaciones`),
  UNIQUE INDEX `idactulisaciones_UNIQUE` (`idactulisaciones` ASC) ,
  INDEX `fk_actulisaciones_1_idx` (`idTrabajos` ASC) ,
  INDEX `fk_actulisaciones_2_idx` (`idreparaciones` ASC),
  CONSTRAINT `fk_actulisaciones_1`
    FOREIGN KEY (`idTrabajos`)
    REFERENCES `dbcyber`.`Trabajos` (`idTrabajos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actulisaciones_2`
    FOREIGN KEY (`idreparaciones`)
    REFERENCES `dbcyber`.`Reparaciones` (`idReparaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
